server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: security-003-springcloud
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: root
